### ISSUE TITLE
Error - 2018/05/31 15:53:36 [0] Could not login: rpc error: code = InvalidArgument desc = JGrpcServer: Client Id jti already exists

### ISSUE THREAD

**Issue by mnanduri** [nileshsimaria/jtimon#10]
It was working before and it stopped, getting below error. Any ideas?

2018/05/31 15:53:24 batch size: 1048576 batch frequency: 2000
2018/05/31 15:53:24 Successfully initialized InfluxDB Client
2018/05/31 15:53:24 Connecting to 192.168.1.139:50051
2018/05/31 15:53:26 gRPC headers from host 192.168.1.139:50051
2018/05/31 15:53:26   content-type: [application/grpc]
2018/05/31 15:53:26   grpc-accept-encoding: [identity,deflate,gzip]
2018/05/31 15:53:26 Receiving telemetry data from 192.168.1.139:50051
2018/05/31 15:53:26 &{0xc420012a80 0x55f9e46d95e0 192.168.1.139:50051 {passthrough  192.168.1.139:50051} 192.168.1.139:50051 {<nil> <nil> <nil> <nil> {120000000000 1000000000 1.6 0.2} false true 0 <nil> {grpc-go/1.11.3  0x55f9e495bb80 false [] <nil> {0 0 false} 0xc42000e288 524288 0 0 0} [] <nil> 0x55f9e50f2778 false} 0xc420133a40 {<nil> 0x55f9e495bb80} 0xc420141f20 0xc420012a40 {{0 0} 0 0 0 0} {<nil> map[]}  map[0xc4200738c0:{}] {0 0 false} pick_first  [{192.168.1.139:50051 0  <nil>}] 0xc420012bc0}.TelemetrySubscribe(_) = _, rpc error: code = Unknown desc = Authorization failed
2018/05/31 15:53:36 Reconnecting to 192.168.1.139:50051
2018/05/31 15:53:36 [0] Could not login: rpc error: code = InvalidArgument desc = JGrpcServer: Client Id jti already exists
^C2018/05/31 15:53:44 

Collector Stats for 192.168.1.139:50051 (Run time : 19.962453879s)
0            : in-packets

**Comment by nileshsimaria** [comment]
<pre>
2018/05/31 15:53:36 [0] Could not login: rpc error: code = InvalidArgument desc = JGrpcServer: Client Id jti already exists
</pre>

You need to give unique client IDs if multiple clients are subscribing telemetry data from the server.

**Comment by mnanduri** [comment]
Is this the one? I have changed this and it did not work.

 "cid": "jti",

**Comment by nileshsimaria** [comment]
yes thats the one. Also you have other errors. check your username/pwd as well.

<pre>
0xc420012bc0}.TelemetrySubscribe(_) = _, rpc error: code = Unknown desc = Authorization failed
2018/05/31 15:53:36 Reconnecting to 192.168.1.139:50051
</pre>

**Comment by mnanduri** [comment]
It started working once i stopped the other server. I had two grpc clients.
The above error also goes away when i stop the other server.

**Comment by nileshsimaria** [comment]
You can do multiple server and multiple clients as long as client ids are
unique for a server and you supply right credentials.
