### ISSUE TITLE
About Kafka and/or logstash support

### ISSUE THREAD

**Issue by hz2102** [nileshsimaria/jtimon#14]
Hi,

Do you have plan to support other tools like kafka, logstash, elastic search etc.

If you have any kind of plans for supporting please let me know.

Regards,
HZ2102

**Comment by nileshsimaria** [comment]
I do have plans to support Kafka integration.

**Comment by hz2102** [comment]
Hi @nileshsimaria , 

Just to check, is there any progress on this enhancement.
Regards,
hz2102
