### ISSUE TITLE
Running with prometheus parameter

### ISSUE THREAD

**Issue by tom-myny** [nileshsimaria/jtimon#18]
If we run jtimon with the parameter --prometheus we get the following error:

root@opennti:~# gocode/bin/jtimon --config juniper.json --prometheus
Version: version-not-available BuildTime build-time-not-available
listen tcp: invalid port 842350541320

Also with prometheus-port:

root@opennti:~# gocode/bin/jtimon --config juniper.json --prometheus --prometheus-port 8090
Version: version-not-available BuildTime build-time-not-available
listen tcp: invalid port 842350541264

We see that the program is not listening on port 8090
If we run it without the prometheus parameter we see no port error:

root@opennti:~# gocode/bin/jtimon --config juniper.json
Version: version-not-available BuildTime build-time-not-available

**Comment by iDemonix** [comment]
Same here:

```
[root@localhost jtimon]$./jtimon --config test.json --prometheus --prometheus-port 9003
Version: version-not-available BuildTime build-time-not-available
listen tcp: address 812354562524: invalid port
```

Works without the prometheus flags

**Comment by awlx** [comment]
Same error here :/.
