### ISSUE TITLE
periodic stats not working?

### ISSUE THREAD

**Issue by zhanghaofeng** [nileshsimaria/jtimon#22]
I am looking for periodic stats from the collector, but I get nothing. 

root@yangtze:~/hfzhang/D101# ./jtimon --config d102.json
Version: version-not-available BuildTime build-time-not-available
2018/08/24 11:03:00 logging in d102.test.log for 1.100.0.0:10162 [periodic stats every 2 seconds]

Here is my json file.

{
    "host": "1.100.0.0",
    "port": 10162,
    "user": "regress",
    "password": "MaRtInI",
    "cid": "cid-yangtze-d100-3",
    "influx" : {
        "server" : "127.0.0.1",
        "port" : 8086,
        "dbname" : "tinyvale_kv",
        "measurement" : "OC",
        "user" : "influx",
        "password" : "influxdb",
        "recreate" : true
    },
    "tls" : {
        "clientcrt" : "client/client.crt",
        "clientkey" : "client/client.key",
        "ca" : "CA/RootCA.crt",
        "servername" : "tinyvale"
    },
    "grpc" : {
        "ws" : 1048576
    },
    "paths": [
    ...
    ],
    "log": {
        "file": "d102.test.log",
        "verbose": true,
        "periodic-stats": 2,
        "drop-check": true,
        "latency-check": false,
        "csv-stats": true,
        "FileHandle": null,
        "Logger": null
    }
}

**Comment by nileshsimaria** [comment]
Can you try with the latest jtimon ?

**Comment by nileshsimaria** [comment]
Sorry for the late reply, just got chance to work on this one. On top of JSON config for periodic-stats, you need to enable stats handler of grpc using the command line. Following should work.

```
$ ./jtimon --stats-handler --config d102.json
```
