### ISSUE TITLE
TelemetrySubscribe(_) = _, rpc error: code = Unknown desc = Authorization failed

### ISSUE THREAD

**Issue by maxbaldi** [nileshsimaria/jtimon#23]
Hi,
i am run the following command:
./jtimon --config test.json --gtrace --print

and the result is the following:

2018/09/20 04:41:36 Connecting to 10.49.169.179:50051
2018/09/20 04:41:36 gRPC headers from host 10.49.169.179:50051
2018/09/20 04:41:36   content-type: [application/grpc]
2018/09/20 04:41:36   grpc-accept-encoding: [identity,deflate,gzip]
2018/09/20 04:41:36 Receiving telemetry data from 10.49.169.179:50051
2018/09/20 04:41:36 &{0xc8200152c0 0x6a7340 10.49.169.179:50051 {passthrough  10.49.169.179:50051} 10.49.169.179:50051 {<nil> <nil> <nil> <nil> {120000000000 1000000000 1.6 0.2} false true 0 <nil> {grpc-go/1.11.3  0x5556f0 false [] <nil> {0 0 false} <nil> 524288 0 0 0} [] <nil> 0xecd8a8 false} 0xc82015ebe0 {<nil> 0x5556f0} 0xc82014dc80 0xc820015280 {{0 0} 0 0 0 0} {<nil> map[]}  map[0xc820160b40:{}] {0 0 false} pick_first  [{10.49.169.179:50051 0  <nil>}] 0xc820015580}.TelemetrySubscribe(_) = _, rpc error: code = Unknown desc = Authorization failed
2018/09/20 04:41:36 Restarting the connection
2018/09/20 04:41:36 Retrying the connection

the user correctly login into the node but it seems there is something wrong with authorization.

Regards,
Max

**Comment by nileshsimaria** [comment]
Have you provided user credentials in config file ?
