### ISSUE TITLE
jtimon not working

### ISSUE THREAD

**Issue by ayubsyz** [nileshsimaria/jtimon#26]
This was working earlier. Not sure what went wrong. Any Clue? Tried changing cid, still see same issue.

#  /root/bin/jtimon --config srx4600_components_jtimon.cfg --print

2018/10/30 10:15:45 Connecting to 10.157.68.230:50052
2018/10/30 10:15:45 [0] Could not login: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 500 Domain Not Found\\r\\nContent-Length: 246\\r\\nAccept-Ranges: bytes\\r\\nCache-Control: private, no-cache\\r\\nConnection: keep-alive\\r\\nConnection: keep-alive\\r\\nContent-Type: text/html\\r\\nDate: Tue, 30 Oct 2018 17:15:42 GMT\\r\\nRetry-After: 0\\r\\nServer: Varnish\\r\\nVia: 1.1 varnish\\r\\nX-Served-By: cache-sjc3139-SJC\\r\\n\\r\\n\\n<html>\\n<head>\\n<title>Fastly error: unknown domain 10.157.68.230</title>\\n</head>\\n<body>\\n<p>Fastly error: unknown domain: 10.157.68.230. Please check that this domain has been added to a service.</p>\\n<p>Details: cache-sjc3139-SJC</p></body></html>\""
All done ... exiting!

**Comment by nileshsimaria** [comment]
Looks like connection/environment issue. Can you retry ?

**Comment by nileshsimaria** [comment]
Closing as it seems connection / env issue. Reach out if its not.
