### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by door7302** [nileshsimaria/jtimon#28]
Hello 

i can not succeed to build the latest jtimon image. I faced this issue : 

root@muztc871:/home/david/telemetry/jtimon# go version
go version go1.10.3 linux/amd64

root@muztc871:/home/david/telemetry/jtimon# go build
# _/home/david/telemetry/jtimon
./main.go:205:37: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/nileshsimaria/jtimon/vendor/google.golang.org/grpc".ClientConn in argument to authentication.NewLoginClient
./subscribe.go:101:41: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/nileshsimaria/jtimon/vendor/google.golang.org/grpc".ClientConn in argument to telemetry.NewOpenConfigTelemetryClient

Could you help me to fix this ? I need latest version of jtimon to have gnmi options.

BR
David

**Comment by nileshsimaria** [comment]
There are two ways to build it correctly. Choose the one works best for you.

### go get

- Set your GOPATH
- go get github.com/nileshsimaria/jtimon
- go get will get the code from github, build the source. Find binary at $GOPATH/bin/jtimon

### git clone
- set your GOPATH
- mkdir -p $GOPATH/src/github.com/nileshsimaria
- cd $GOPATH/src/github.com/nileshsimaria
- git clone https://github.com/nileshsimaria/jtimon.git
- cd jtimon
- go build or use make to build
