### ISSUE TITLE
Couple of optimization in influx.go

### ISSUE THREAD

**Issue by sriram-rsankar** [nileshsimaria/jtimon#31]
There is couple of optimization possibilities in  influx.db.

1) Instead of calling client.NewPoint for every point, points can be accumulated and client.Newpoint can be called in the end.
2) Minor optimisation in prefix

Attached untested diff with these optimisation. 

[jtimon.txt](https://github.com/nileshsimaria/jtimon/files/2655967/jtimon.txt)

**Comment by nileshsimaria** [comment]
fixed.
