### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by stelucz** [nileshsimaria/jtimon#55]
Hi,

after latest commits docker image size grew almost 25 times.
Image build before https://github.com/nileshsimaria/jtimon/commit/e8782ca3a4a29d04e2e394d609c9a5fbdbd798e4
```
REPOSITORY        TAG                 IMAGE ID            CREATED             SIZE
jtimon            latest              88df549101f1        5 days ago          17.4MB
```

Image build today after https://github.com/nileshsimaria/jtimon/commit/1171e8059f576e559602ec9b584db4402fa8b136
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jtimon              latest              91672f0036b0        8 minutes ago       437MB
```
**17.4MB** vs **437MB** size

Was a such huge difference in image size planned or it is bug? Thanks!

Regards,
Lukas

**Comment by nileshsimaria** [comment]
Thanks @stelucz. It was a bug. I have used multi-stage docker build to reduce image size.

```
$ docker images | grep jtimon
jtimon              latest              2d44fb9577ac        4 minutes ago       20.5MB
```
