### ISSUE TITLE
[Question] Junos Telemetry and prometheus

### ISSUE THREAD

**Issue by igolka6662** [nileshsimaria/jtimon#6]
Hello.

I'm interested in capturing Junos telemetry: https://www.juniper.net/documentation/en_US/junos/topics/concept/junos-telemetry-interface-export-format-understanding.html

Does it support it?

Also I saw the Prometheus CLI parameter, can you please provide the instructions how to configure the data output to Prometheus?

Thanks,
Dmitry

**Comment by nileshsimaria** [comment]
It supports gRPC telemetry only (no UDP support).

Prometheus param is just to monitor jtimon binary itself (number of go routines, etc).

jtimon supports inserting data onto influxdb.

**Comment by nileshsimaria** [comment]
Hi Dmitry,

I've added Prometheus support in JTIMON. Now collected Junos telemetry would get exported to Prometheus also. Run it with --prometheus.

Thanks,
Nilesh
