### ISSUE TITLE
about data format

### ISSUE THREAD

**Issue by hz2102** [nileshsimaria/jtimon#7]
Hi,

I am thinking of using this tool for collecting MX telemetry info in a multi-vendor environment.
My question is, is there any kind of feature available in this tool to change the format to JSON?

MX, my primary target for checking telemetry, supports GPB format for encoding only (GPB-SDM too?).
On the other hand i need the data to be in JSON format.
So if there is any kind of feature available please let me know.

Regards,
hz2102

**Comment by nileshsimaria** [comment]
JSON support is not there. Also this tool supports only gRPC telemetry.

**Comment by hz2102** [comment]
Thanks :)
I understand about JSON support and gRPC part.

Regards,
hz2102

**Comment by nileshsimaria** [comment]
Hi hz2102,

JTIMON now has JSON support. 

https://github.com/nileshsimaria/jtimon/wiki/JSON

**Comment by Netone-OpenMSA-Dev-Team** [comment]
Thank you so much. nileshsimaria!
I will check this function and get back to you if there is any kind of problems/ issues.

Regards,
hz2102
