### ISSUE TITLE
compilation issue 

### ISSUE THREAD

**Issue by tkaagent** [nileshsimaria/jtimon#75]
To accomodate new client I did:
go get github.com/influxdata/influxdb1-client/v2 \

then, declaration section of your Go file, paste the following: import "github.com/influxdata/influxdb1-client/v2".  

I am getting this error once trying to compile:

`tkaagent@ubuntu1:~/jtimon$ sudo go build
# _/home/tkaagent/jtimon
./subscribe_cisco_iosxr.go:198:33: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/nileshsimaria/jtimon/vendor/google.golang.org/grpc".ClientConn in argument to IOSXRExtensibleManagabilityService.NewGRPCConfigOperClient
./subscribe_juniper_junos.go:105:41: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/nileshsimaria/jtimon/vendor/google.golang.org/grpc".ClientConn in argument to "github.com/nileshsimaria/jtimon/telemetry".NewOpenConfigTelemetryClient
./subscribe_juniper_junos.go:228:32: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/nileshsimaria/jtimon/vendor/google.golang.org/grpc".ClientConn in argument to authentication.NewLoginClient
tkaagent@ubuntu1:~/jtimon$`

**Comment by nileshsimaria** [comment]
use go build with -mod=vendor to solve this.
