### ISSUE TITLE
Getting error with go build

### ISSUE THREAD

**Issue by mnanduri** [nileshsimaria/jtimon#8]
I followed the steps and when doing go build, getting the below error, any ideas?

./main.go:195: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/nileshsimaria/jtimon/vendor/google.golang.org/grpc".ClientConn in argument to authentication.NewLoginClient
./subscribe.go:81: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/nileshsimaria/jtimon/vendor/google.golang.org/grpc".ClientConn in argument to telemetry.NewOpenConfigTelemetryClient
./subscribe_gnmi.go:115: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/nileshsimaria/jtimon/vendor/google.golang.org/grpc".ClientConn in argument to gnmi.NewGNMIClient

**Comment by nileshsimaria** [comment]
go build gives priority to packages from $GOPATH. Try removing the one 
$ rm -fr $GOPATH/src/google.golang.org/grpc

Once its gone, it will be picked up from vendor directory at build time.

**Comment by nileshsimaria** [comment]
Also please make sure you build source inside GOPATH. Go build does not work outside GOPATH.

**Comment by mnanduri** [comment]
Got it, thanks.

On a side note, are the return values stored in influxdb, if so, how can I access them?

**Comment by nileshsimaria** [comment]
Yes, it supports inserting into influxDb. You can use influxdb's api to query data or use "influx" program to run sql style queries. See below sample config to insert data in influxdb running on localhost.

<pre>
{
    "host": "server-serving-telemetry-data,
    "port": 32767,
    "cid": "my-client-id",
    "influx": {
        "server": "127.0.0.1"
        "port": 8086,
        "dbname": "db",
        "measurement": "m"
    },
    "log": {
        "file": "jtimon.log",
        "periodic-stats": 0
    },
    "paths": [
        {
            "freq": 10000,
            "path": "/interfaces"
        }
    ]
}
</pre>

**Comment by mnanduri** [comment]
Thanks for the snippet. Got it working now.
