### ISSUE TITLE
Cannot make docker image 'cannot load protobuf descriptor'

### ISSUE THREAD

**Issue by NosIreland** [nileshsimaria/jtimon#82]
Hi,
I no longer seem to be able to make docker image and getting the error below:
'build github.com/nileshsimaria/jtimon: cannot load github.com/golang/protobuf/protoc-gen-go/descriptor: open /go/src/app/vendor/github.com/golang/protobuf/protoc-gen-go/descriptor: no such file or directory'
Any guidance what could be causing this?
Thank you.

**Comment by nileshsimaria** [comment]
Sorry for the breakage. Can you try now, it's fixed.

**Comment by NosIreland** [comment]
> 
> 
> Sorry for the breakage. Can you try now, it's fixed.
Yes, all good now.
Thanks
